# Generated by Django 4.2.30 on 2026-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_batch_class_days_feepackage_class_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='police_station',
            field=models.CharField(blank=True, choices=[('Thenhipalam Police Station', 'Thenhipalam Police Station'), ('Tirurangadi Police Station', 'Tirurangadi Police Station'), ('Vengara Police Station', 'Vengara Police Station'), ('Kondotty Police Station', 'Kondotty Police Station'), ('Vazhakkad Police Station', 'Vazhakkad Police Station'), ('Malappuram Police Station', 'Malappuram Police Station')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='second_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feepackage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
