# Generated by Django 4.2.30 on 2026-06-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_policestation_alter_student_police_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
